language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r Team-Coder *
  - mkdir -p deploy
  - ls -al
  - mv Team-Coder.zip deploy/Team-Coder.zip
  - ls -al deploy

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY   # travis settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY  # travis settings에 설정된 값
    bucket: teamcoder-build     # s3 버킷
    region: ap-northeast-2
    cleanup: false  # skip_cleanup: true 에서 변경(deprecated)
    acl: private    # zip 파일 접근을 private로
    #wait_until_deployed: true
    #local_dir: deploy   # before_deploy에서 생성한 디렉토리

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamcoder-build     # s3 버킷
    key: Team-Coder.zip   # 빌드 파일을 압축해서 전달
    bundle_type: zip  # 압축 확장자
    application: teamcoder-webservice   # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: teamcoder-webservice-group  # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    cleanup: false  # skip_cleanup: true 에서 변경(deprecated)
    wait_until_deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - ljo0831@naver.com
